/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package screen;

import java.util.Collection;
import java.util.Collections;
import java.util.Stack;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import main.token.CaracterAnalisadoInfo;

import static utils.Utils.reverseStack;

/**
 *
 * @author jeanfernandes
 */
public class CodeEditor extends javax.swing.JFrame {
    
    private ActionCodeEditor actions;

    /**
     * Creates new form CodeEditor
     */
    public CodeEditor() {
        initComponents();
        this.actions = new ActionCodeEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        codeArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        validacoes = new javax.swing.JList<>();
        status = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        compile = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tokens = new javax.swing.JTable();
        limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setRowHeaderView(codeArea);

        codeArea.setColumns(20);
        codeArea.setLineWrap(true);
        codeArea.setRows(5);
        jScrollPane1.setViewportView(codeArea);

        jScrollPane2.setViewportView(validacoes);

        status.setEditable(false);

        save.setText("Salvar");
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcaoBtnSave(evt);
            }
        });

        compile.setText("Compilar");
        compile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acaoBtnCompile(evt);
            }
        });

        tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        this.tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Palavra", "TOken"
            }
        ));
        jScrollPane3.setViewportView(tokens);

        limpar.setText("Limpar");
        limpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acaoBtnLimpar(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(limpar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(compile)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(compile)
                    .addComponent(limpar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcaoBtnSave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcaoBtnSave
        // TODO add your handling code here:
        this.actions.salvar(this.codeArea.getText());
        this.status.setText("ARQUIVO SALVO");
    }//GEN-LAST:event_AcaoBtnSave

    private void acaoBtnCompile(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acaoBtnCompile
        // TODO add your handling code here:
        this.status.setText("COMPILANDO");
        this.actions.compile();
        this.status.setText(this.actions.getStatusCompilacao());
        
        Collection<String> mensagensValidacao = this.actions.getMensagensValidacao();
        
        String[] toArray = mensagensValidacao.toArray(new String[0]);
        
        this.validacoes.setListData(toArray);
        Stack<CaracterAnalisadoInfo> pilha = this.actions.getPilha();
        reverseStack(pilha);

        DefaultTableModel model = (DefaultTableModel) this.tokens.getModel();

        for (int i = pilha.size(); i >= 0; i--) {
            CaracterAnalisadoInfo info = pilha.pop();
            model.addRow(new Object[]{info.getValor(), info.getToken().getSimbolo()});   
        }
    }//GEN-LAST:event_acaoBtnCompile

    private void acaoBtnLimpar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acaoBtnLimpar
        // TODO add your handling code here:
        this.status.setText("LIMPO");
        this.validacoes.setListData(new String[0]);
        this.tokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
            },
            new String [] {
                "Palavra", "TOken"
            }
        ));
    }//GEN-LAST:event_acaoBtnLimpar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea codeArea;
    private javax.swing.JButton compile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpar;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JTable tokens;
    private javax.swing.JList<String> validacoes;
    // End of variables declaration//GEN-END:variables
}
